/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserListDialog.java
 *
 * Created on 2010/10/17, 16:55:08
 */

package twitter.gui.form;

import java.util.List;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import twitter.action.TweetUserTimelineGetter;
import twitter.gui.action.TweetMainAction;
import twitter.gui.component.TweetListTableModel;
import twitter.manage.TweetManager;
import twitter4j.UserList;

/**
 *
 * @author nishio
 */
public class UserListDialog extends javax.swing.JDialog {

    //メインアクション
    private TweetMainAction mainAction = null;
    //tweetmanager
    private TweetManager tweetManager = null;
    //リストを取得するユーザの名前
    private String listUserName = null;
    //リストモデル
    private TweetListTableModel listTableModel = new TweetListTableModel();
    //アイコンの大きさ
    private static final int iconSize = 50;

    /** Creates new form UserListDialog */
    public UserListDialog(java.awt.Frame parent, boolean modal, TweetMainAction mainAction,
            TweetManager tweetManager, String listUserName) {
        super(parent, modal);
        initComponents();
        this.tweetManager = tweetManager;
        this.mainAction = mainAction;
        this.listUserName = listUserName;

        addUserListToTable(listUserName);
    }

    /**
     * テーブルにリスト一覧を挿入
     * @param username
     */
    public void addUserListToTable(String username) {
        this.listTableModel.clearStatus();
        this.setTableEnvironment();
        if( this.tweetManager != null ) {
            List<UserList> list = this.tweetManager.getUserLists(username);
            for(UserList u : list ) {
                this.listTableModel.insertUserList(u);
            }
        }
    }

    /**
     * テーブルの大きさ等の情報を設定
     */
    public void setTableEnvironment() {
        TableColumnModel columnModel = this.jTable1.getColumnModel();
        TableColumn column = columnModel.getColumn(0);
        column.setMinWidth( this.iconSize );
        column.setMaxWidth( this.iconSize );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(listTableModel);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("OK");

        jButton2.setText("キャンセル");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
