CREATE TABLE IF NOT EXISTS TWEET(
	id INTEGER PRIMARY KEY,
	following TEXT,
	date TEXT,
	replyStatusID INTEGER,
	replyUserID INTEGER,
	text TEXT,
	created TEXT,
	description TEXT,
	userFavorite INTEGER,
	followers INTEGER,
	friend INTEGER,
	userId INTEGER,
	lang TEXT,
	location TEXT,
	name TEXT,
	profileBackgroundColor TEXT,
	profileBackgroundImageURL TEXT,
	profileImageURL TEXT,
	profileSidebarBorderColor TEXT,
	profileSidebarFillColor TEXT,
	profileTextColor TEXT,
	screenName TEXT,
	statusesCount INTEGER,
	timeZone TEXT,
	url TEXT,
	utc INTEGER,
	contributorsEnable TEXT,
	geoEnable TEXT,
	profileBackgroundTiled TEXT,
	isProtected TEXT,
	verified TEXT,
	source TEXT,
	favorite TEXT,
	retweet TEXT,
	truncated TEXT
);

	
